### ISSUE TITLE
module not found formidable middleware

### ISSUE THREAD

**Issue by game5413** [nanoexpress/middlewares#21]
### Is you/your team sponsoring this project

- [ ] Yes
- [x] No

### Minimal reproducible repo

[https://github.com/nanoexpress/middlewares/tree/master/packages/formidable](https://github.com/nanoexpress/middlewares/tree/master/packages/formidable)

### Current Behavior

`const formidable = require('@nanoexpress/middleware-formidable/cjs');`

got an error with message:
```
Error: Cannot find module 'D:\www\nano\node_modules\@nanoexpress\middleware-formidable\cjs\file-upload.cjs.js'
. Please verify that the package.json has a valid "main" entry
     at tryPackage (internal/modules/cjs/loader.js:308:19)
     at Function.Module._findPath (internal/modules/cjs/loader.js:521:18)
     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:872:27)
     at Module.Hook._require.Module.require (D:\www\nano\node_modules\require-in-the-middle\index.js:61:29)
     at require (internal/modules/cjs/helpers.js:88:18)
     at Object.<anonymous> (D:\www\nano\services\user\middlewares\index.js:2:20)
     at Module._compile (internal/modules/cjs/loader.js:1068:30)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
     at Module.load (internal/modules/cjs/loader.js:933:32)
     at Function.Module._load (internal/modules/cjs/loader.js:774:14) {
   code: 'MODULE_NOT_FOUND',
   path: 'D:\\www\\nano\\node_modules\\@nanoexpress\\middleware-formidable\\cjs\\package.json',
   requestPath: '@nanoexpress/middleware-formidable/cjs'
 }
```

### Expected behavior/code

not getting error exception MODULE_NOT_FOUND

### Environment

- Node/npm version: 14.17.0 / 7.15.0
- OS: Windows 10 Home
- Addinational Info: @nanoexpress/middleware-formidable:1.1.0

### Possible Solution
modify main file on package.json

[Pull Request #20 ](https://github.com/nanoexpress/middlewares/pull/20)

### Additional context/Screenshots

![image](https://user-images.githubusercontent.com/37659721/120836046-557a3680-c58f-11eb-896e-99605b0091fa.png)

### Note

- already tested on local by editing main file on node_modules folder

**Comment by dalisoft** [comment]
I merged your PR

**Comment by dalisoft** [comment]
But will not release new version due of not valid commit message

**Comment by game5413** [comment]
ahh.. i see, i'm focusing with format PR message so not see that commit message have an format too.

**Comment by game5413** [comment]
can it trigger manually ?

**Comment by dalisoft** [comment]
@game5413 Seems there semantic release bug. I am tried many times, does not releases. Manually i cannot do as then all of submodules gets out of sync

**Comment by game5413** [comment]
Thank you for your help 👍
